//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Nova_Examples_Colorless_Scripts_InterludeControllerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Nova.Examples.Colorless.Scripts.InterludeController), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Play", Play);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("chapterSpritePath", get_chapterSpritePath, set_chapterSpritePath);
		L.RegVar("holdingDuration", get_holdingDuration, set_holdingDuration);
		L.RegVar("BackgroundSprite", get_BackgroundSprite, set_BackgroundSprite);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)ToLua.CheckObject<Nova.Examples.Colorless.Scripts.InterludeController>(L, 1);
			obj.Play();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_chapterSpritePath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			string ret = obj.chapterSpritePath;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chapterSpritePath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_holdingDuration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			float ret = obj.holdingDuration;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index holdingDuration on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackgroundSprite(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			UnityEngine.Sprite ret = obj.BackgroundSprite;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BackgroundSprite on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_chapterSpritePath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.chapterSpritePath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chapterSpritePath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_holdingDuration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.holdingDuration = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index holdingDuration on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BackgroundSprite(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.Examples.Colorless.Scripts.InterludeController obj = (Nova.Examples.Colorless.Scripts.InterludeController)o;
			UnityEngine.Sprite arg0 = (UnityEngine.Sprite)ToLua.CheckObject(L, 2, typeof(UnityEngine.Sprite));
			obj.BackgroundSprite = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BackgroundSprite on a nil value");
		}
	}
}

