//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Nova_BackgroundControllerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Nova.BackgroundController), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetImage", SetImage);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("imageFolder", get_imageFolder, set_imageFolder);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Nova.BackgroundController obj = (Nova.BackgroundController)ToLua.CheckObject<Nova.BackgroundController>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetImage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_imageFolder(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.BackgroundController obj = (Nova.BackgroundController)o;
			string ret = obj.imageFolder;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index imageFolder on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_imageFolder(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Nova.BackgroundController obj = (Nova.BackgroundController)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.imageFolder = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index imageFolder on a nil value");
		}
	}
}

